name: 'Check-Title'

on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: MeilCli/regex-match@master
        id: regex
        with:
          regex_pattern: 'test: .*'
          regex_option: 'g'
          search_string: ${{ github.event.pull_request.title }}
      - id: success
        if: steps.regex.outputs.matched == 'true'
        run: echo "::set-output name=result::success"
      - id: failure
        if: steps.regex.outputs.matched != 'true'
        run: echo "::set-output name=result::failure"
      - uses: MeilCli/check-run-auto@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          name: 'Check/Title'
          output_title: 'Check Title Result'
          output_surmmary: 'Check Title of pull request'
          result: ${{ steps.success.outputs.result }}${{ steps.failure.outputs.result }}
