name: 'Check-Issue-Title-By-Comment'

on:
  issues:
    types: [opened, edited, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: MeilCli/regex-match@master
        id: regex
        with:
          regex_pattern: 'test: .*'
          regex_option: 'g'
          search_string: ${{ github.event.issue.title }}
      - uses: MeilCli/hidable-comment-action@master
        with:
          number: ${{ github.event.issue.number }}
          show: ${{ steps.regex.outputs.matched == 'false' }}
          id: 'title-lint'
          body: 'title lint  \n- test1\n- test2\n- test3'
