
name: 'Example regex match'

on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: MeilCli/regex-match@master
        id: regex
        with:
          regex_pattern: 'test: ([a-z]{1,10})([0-9])'
          search_string: 'test: abc9'
      - run: echo 'group1 $group1'
        env:
          group1: ${{ fromJSON(steps.regex.outputs.matched_json)[1] }}
